import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1>Safe Space</h1>
    <form className="my-form">
      <div className="input-wrapper">
        <label htmlFor="start">Where are you?</label>
        <input type="text" id="start" name="start" />
      </div>

      <div className="input-wrapper">
        <label htmlFor="end">Where do you want to go to?</label>
        <input type="text" id="end" name="end" />
      </div>
      <button>Get route</button>
    </form>

      </main>
    </>
  )
}
